export const uz = {
    dashboard: "Dashboard",
    events: "Tadbirlar",
    organizers: "Tashkilotchilar",
    users: "Talabalar",
    admins: "Adminlar",
    requests: "So'rovlar",
    create: "Yaratish",
    edit: "Tahrirlash",
    delete: "O'chirish",
    save: "Saqlash",
    cancel: "Bekor qilish",
    back: "Orqaga",
    search: "Qidirish",
    status: "Holat",
    active: "Aktiv",
    disabled: "O'chirilgan",
    approve: "Tasdiqlash",
    reject: "Rad etish",
};
